print('What is Number 1?')
One = int(input())
print('What is Number 2?')
Two = int(input())
print('What is Number 3?')
Three = int(input())
print('Sum: ' + str(One + Two + Three))
print('Product: ' + str(One * Two * Three))
print('Average: ' + str((One + Two + Three)/3))